platform :ios, '9.0'

target 'Realmsample' do

  use_frameworks!

  # Pods for Realmsample
  pod 'RealmSwift'
  pod 'SwipeCellKit'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
